package com.yongda.ainativeagent.chat.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class ChatColorScheme(
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceRecessed: Color,
    val surfaceVariant: Color,
    val borderSubtle: Color,
    val border: Color,
    val borderInteractive: Color,
    val borderHighlight: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val brand: Color,
    val brandContainer: Color,
    val amber: Color,
    val amberContainer: Color,
    val userBubble: Color,
    val onUserBubble: Color,
    val onBrand: Color,
    val error: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val success: Color,
    val dockSurface: Color,
    val dockControl: Color,
    val brandGradientStart: Color,
    val brandGradientEnd: Color,
)

val LightChatColors = ChatColorScheme(
    background = Color(0xFFF5F5F2),
    surface = Color(0xFFFAF9F6),
    surfaceRaised = Color(0xFFFFFFFF),
    surfaceRecessed = Color(0xFFEEECE6),
    surfaceVariant = Color(0xFFF5F5F4),
    borderSubtle = Color(0x12464137),
    border = Color(0x1C464137),
    borderInteractive = Color(0x24464137),
    borderHighlight = Color(0xD9FFFFFF),
    textPrimary = Color(0xFF1C1917),
    textSecondary = Color(0xFF78716C),
    textTertiary = Color(0xFF706B66),
    brand = Color(0xFFCC785C),
    brandContainer = Color(0xFFF8ECE7),
    amber = Color(0xFFD97706),
    amberContainer = Color(0xFFFFFBEB),
    userBubble = Color(0xFF0F172A),
    onUserBubble = Color.White,
    onBrand = Color.White,
    error = Color(0xFFE11D48),
    errorContainer = Color(0xFFFFF1F2),
    onErrorContainer = Color(0xFF9F1239),
    success = Color(0xFF10B981),
    dockSurface = Color(0xFFFAF9F6),
    dockControl = Color(0xFFEEECE6),
    brandGradientStart = Color(0xFFCC785C),
    brandGradientEnd = Color(0xFFB8664E),
)

val DarkChatColors = ChatColorScheme(
    background = Color(0xFF18181B),
    surface = Color(0xFF202023),
    surfaceRaised = Color(0xFF27272A),
    surfaceRecessed = Color(0xFF141416),
    surfaceVariant = Color(0xFF27272A),
    borderSubtle = Color(0x0FFFFFFF),
    border = Color(0x1AFFFFFF),
    borderInteractive = Color(0x26FFFFFF),
    borderHighlight = Color(0x14FFFFFF),
    textPrimary = Color(0xFFF4F4F5),
    textSecondary = Color(0xFFA1A1AA),
    textTertiary = Color(0xFF9999A1),
    brand = Color(0xFFE08A6F),
    brandContainer = Color(0xFF3B2A24),
    amber = Color(0xFFFBBF24),
    amberContainer = Color(0xFF451A03),
    userBubble = Color(0xFF27272A),
    onUserBubble = Color(0xFFF4F4F5),
    onBrand = Color.White,
    error = Color(0xFFFB7185),
    errorContainer = Color(0xFF4C0519),
    onErrorContainer = Color(0xFFFDA4AF),
    success = Color(0xFF34D399),
    dockSurface = Color(0xFF27272A),
    dockControl = Color(0xFF3F3F46),
    brandGradientStart = Color(0xFFE08A6F),
    brandGradientEnd = Color(0xFFC96F55),
)

internal val LocalChatColors = staticCompositionLocalOf { LightChatColors }
